# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_synoptiquesatlas.ui'
#
# Created: Fri May 25 16:27:11 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SynoptiquesAtlas(object):
    def setupUi(self, SynoptiquesAtlas):
        SynoptiquesAtlas.setObjectName(_fromUtf8("SynoptiquesAtlas"))
        SynoptiquesAtlas.setWindowModality(QtCore.Qt.NonModal)
        SynoptiquesAtlas.resize(507, 460)
        SynoptiquesAtlas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox = QtGui.QDialogButtonBox(SynoptiquesAtlas)
        self.buttonBox.setGeometry(QtCore.QRect(0, 410, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.lblGrille = QtGui.QLabel(SynoptiquesAtlas)
        self.lblGrille.setGeometry(QtCore.QRect(90, 70, 41, 51))
        self.lblGrille.setFrameShape(QtGui.QFrame.Box)
        self.lblGrille.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblGrille.setLineWidth(1)
        self.lblGrille.setMidLineWidth(0)
        self.lblGrille.setText(_fromUtf8(""))
        self.lblGrille.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/synoptiquesatlas/grille.png")))
        self.lblGrille.setScaledContents(True)
        self.lblGrille.setObjectName(_fromUtf8("lblGrille"))
        self.gridLayoutWidget = QtGui.QWidget(SynoptiquesAtlas)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 200, 444, 150))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cbbComp = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbbComp.setObjectName(_fromUtf8("cbbComp"))
        self.gridLayout.addWidget(self.cbbComp, 1, 2, 1, 1)
        self.lblComp = QtGui.QLabel(self.gridLayoutWidget)
        self.lblComp.setObjectName(_fromUtf8("lblComp"))
        self.gridLayout.addWidget(self.lblComp, 1, 0, 1, 1)
        self.overlapInp = QtGui.QLineEdit(self.gridLayoutWidget)
        self.overlapInp.setText(_fromUtf8("0"))
        self.gridLayout.addWidget(self.overlapInp, 5, 2, 1, 1)
        self.lblOverlap = QtGui.QLabel(self.gridLayoutWidget)
        self.lblOverlap.setObjectName(_fromUtf8("lblOverlap"))
        self.gridLayout.addWidget(self.lblOverlap, 5, 0, 1, 1)
        self.lieOutDir = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lieOutDir.setText(_fromUtf8(""))
        self.lieOutDir.setObjectName(_fromUtf8("lieOutDir"))
        self.gridLayout.addWidget(self.lieOutDir, 4, 2, 1, 1)
        self.lblOutDir = QtGui.QLabel(self.gridLayoutWidget)
        self.lblOutDir.setObjectName(_fromUtf8("lblOutDir"))
        self.gridLayout.addWidget(self.lblOutDir, 4, 0, 1, 1)
        self.btnUpdate = QtGui.QToolButton(self.gridLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/synoptiquesatlas/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.gridLayout.addWidget(self.btnUpdate, 1, 3, 1, 1)
        self.btnShow = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnShow.setObjectName(_fromUtf8("btnShow"))
        self.gridLayout.addWidget(self.btnShow, 1, 4, 1, 1)
        self.btnBrowse = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.gridLayout.addWidget(self.btnBrowse, 4, 4, 1, 1)
        self.lblInLayer = QtGui.QLabel(self.gridLayoutWidget)
        self.lblInLayer.setObjectName(_fromUtf8("lblInLayer"))
        self.gridLayout.addWidget(self.lblInLayer, 0, 0, 1, 1)
        self.cbbInLayer = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbbInLayer.setObjectName(_fromUtf8("cbbInLayer"))
        self.gridLayout.addWidget(self.cbbInLayer, 0, 2, 1, 1)
        self.lblMap = QtGui.QLabel(self.gridLayoutWidget)
        self.lblMap.setObjectName(_fromUtf8("lblMap"))
        self.gridLayout.addWidget(self.lblMap, 2, 0, 1, 1)
        self.cbbMap = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbbMap.setObjectName(_fromUtf8("cbbMap"))
        self.gridLayout.addWidget(self.cbbMap, 2, 2, 1, 1)
        self.btnCreerSyno = QtGui.QPushButton(SynoptiquesAtlas)
        self.btnCreerSyno.setGeometry(QtCore.QRect(150, 370, 201, 27))
        self.btnCreerSyno.setObjectName(_fromUtf8("btnCreerSyno"))
        self.chkGrille = QtGui.QCheckBox(SynoptiquesAtlas)
        self.chkGrille.setGeometry(QtCore.QRect(140, 80, 211, 22))
        self.chkGrille.setObjectName(_fromUtf8("chkGrille"))
        self.chkDyn = QtGui.QCheckBox(SynoptiquesAtlas)
        self.chkDyn.setGeometry(QtCore.QRect(140, 140, 251, 22))
        self.chkDyn.setObjectName(_fromUtf8("chkDyn"))
        self.lblDyn = QtGui.QLabel(SynoptiquesAtlas)
        self.lblDyn.setGeometry(QtCore.QRect(90, 130, 41, 51))
        self.lblDyn.setFrameShape(QtGui.QFrame.Box)
        self.lblDyn.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblDyn.setLineWidth(1)
        self.lblDyn.setMidLineWidth(0)
        self.lblDyn.setText(_fromUtf8(""))
        self.lblDyn.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/synoptiquesatlas/grille_dyn.png")))
        self.lblDyn.setScaledContents(True)
        self.lblDyn.setObjectName(_fromUtf8("lblDyn"))
        self.horizontalLayoutWidget = QtGui.QWidget(SynoptiquesAtlas)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 371, 61))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.aboutButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.aboutButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.aboutButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/synoptiquesatlas/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon1)
        self.aboutButton.setIconSize(QtCore.QSize(30, 30))
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.horizontalLayout.addWidget(self.aboutButton)
        self.lblEntete = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.lblEntete.setFont(font)
        self.lblEntete.setTextFormat(QtCore.Qt.AutoText)
        self.lblEntete.setObjectName(_fromUtf8("lblEntete"))
        self.horizontalLayout.addWidget(self.lblEntete)
        self.helpButton = QtGui.QToolButton(SynoptiquesAtlas)
        self.helpButton.setEnabled(True)
        self.helpButton.setGeometry(QtCore.QRect(460, 10, 36, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButton.sizePolicy().hasHeightForWidth())
        self.helpButton.setSizePolicy(sizePolicy)
        self.helpButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.helpButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/synoptiquesatlas/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon2)
        self.helpButton.setIconSize(QtCore.QSize(30, 30))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))

        self.retranslateUi(SynoptiquesAtlas)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SynoptiquesAtlas.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SynoptiquesAtlas.reject)
        QtCore.QMetaObject.connectSlotsByName(SynoptiquesAtlas)

    def retranslateUi(self, SynoptiquesAtlas):
        SynoptiquesAtlas.setWindowTitle(QtGui.QApplication.translate("SynoptiquesAtlas", "Grids for Atlas", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComp.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Composer :", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOverlap.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Overlap %:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutDir.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Outfiles\n"
"directory :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShow.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInLayer.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Coverage\n"
"layer :", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMap.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Composer\n"
"Map object :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreerSyno.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Create grid(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkGrille.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Generate classic grid", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDyn.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Generate dynamic grid", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEntete.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "Grids for Atlas", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("SynoptiquesAtlas", "...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
